= README

Download, and install https://www.postman.com/downloads/[Postman]

== Testing procedure
* Run the webserver and the `Postman` application
* Go to `new` and select `HTTP Request` in the window
* Set up the test
** GET Tests
+
In the `Untitled Request` tab while the type of request selected is `GET` enter the URL in the URL bar:
+
----
http://localhost:3000/users
----
+
Click `Send` button

** POST Tests
+
In the `Untitled Request` tab while the type of request selected is `POST` enter the URL in the URL bar:
+
----
http://localhost:3000/users
----
*** Under the url bar select `Body`, and then `raw`
*** In the text box below, enter the JSON string
* Click `Send` button
* Observe the output in the window below:
** `Status` value
** the response from the web server in the text box

== Tests:
Run the following tests in sequential order

* Test 1
+
Command
+
----
GET : http://localhost:3000/users
----
+
Expected response
+
----
200 OK : null
----

* Test 2
+
Command
+
----
POST : http://localhost:3000/users : {"FirstName": "Ford", "LastName": "Perfect"}
----
+
Expected response
+
----
200 OK : {"ID":1,"FirstName":"Ford","LastName":"Perfect"}
----

* Test 3
+
Command
+
----
GET : http://localhost:3000/users/1
----
+
Expected response
+
----
200 OK : {"ID":1,"FirstName":"Ford","LastName":"Perfect"}
----

* Test 4
+
Command
+
----
GET : http://localhost:3000/users/3
----
+
Expected response
+
----
500 Internal Server Error :
----

* Test 5
+
Command
+
----
PUT : http://localhost:3000/users/1 : {"ID": 1, "FirstName": "Arthur", "LastName": "Dent"}
----
+
Expected response
+
----
200 OK : {"ID": 1, "FirstName": "Arthur", "LastName": "Dent"}
----

* Test 6
+
Command
+
----
GET : http://localhost:3000/users/1
----
+
Expected response
+
----
200 OK : {"ID": 1, "FirstName": "Arthur", "LastName": "Dent"}
----

* Test 7
+
Command
+
----
DELETE : http://localhost:3000/users/1
----
+
Expected response
+
----
200 OK :
----

* Test 8
+
Command
+
----
GET : http://localhost:3000/users
----
+
Expected response
+
----
200 OK : []
----

